x-base-environment: &base_environment
  DISPLAY: ${DISPLAY}
  XDG_RUNTIME_DIR: /tmp
  QT_X11_NO_MITSHM: "1"

x-ackermann-service: &ackermann_service
  build:
    context: .
    dockerfile: Dockerfile
    args:
      ROS_DISTRO: jazzy
      GZ_VERSION: harmonic
  image: alitekes1/ackermann_sim:latest
  entrypoint: ["/bin/bash"]
  working_dir: /root/colcon_ws
  stdin_open: true
  tty: true

x-shared-volumes: &shared_volumes
  - /tmp/.X11-unix:/tmp/.X11-unix:rw
  - /run/user:/run/user:ro
  - /home/studente/ackermann_sim/src/ackermann-vehicle-gzsim-ros2:/root/colcon_ws/src/ackermann-vehicle-gzsim-ros2

services:
  ackermann_sim:
    <<: *ackermann_service
    container_name: ackermann_sim
    environment:
      <<: *base_environment
      LIBGL_ALWAYS_SOFTWARE: "1"
      GALLIUM_DRIVER: llvmpipe
      MESA_GL_VERSION_OVERRIDE: "4.5"
      MESA_GLSL_VERSION_OVERRIDE: "450"
      MESA_LOADER_DRIVER_OVERRIDE: llvmpipe
      __GLX_VENDOR_LIBRARY_NAME: mesa
      QT_QPA_PLATFORM: xcb
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      ROS_DISABLE_SHARED_MEMORY: "1"
    volumes: *shared_volumes

