#!/usr/bin/env python3
"""
Path Planner Utilities

Shared utilities for path planning scripts including route goals and main execution.
"""

import time
import subprocess
import rclpy
from pathlib import Path
from typing import List, Tuple

# Route goals for testing (A->B, B->C, C->D, ...) - 15 chained routes
# Uncomment one goal at a time to test sequentially
# Each route's goal becomes the next route's start
# NOTE: These coordinates are EXTRACTED FROM ACTUAL ROAD NETWORK in map2gazebo/maps/
# They are guaranteed to be on roads (from centerline_points and nodes_enu)
# IMPORTANT: Keep this list IDENTICAL in both dijkstra_path_planner.py and astar_path_planner.py
# for fair comparison!
# Generated by: map2gazebo/scripts/extract_route_goals.py
ROUTE_GOALS = [
    # Route 1: Current Position -> A (short route)
    # (-0.27, -102.52),
    # Route 2: A -> B (short route)
    # (4.80, -82.97),
    # Route 3: B -> C 
    # (-15.17, -103.69),
    # Route 4: C -> D (medium route)
    # (-21.63, -123.24),
    # Route 5: D -> E (medium route)
    # (-20.17, -143.25),
    # Route 6: E -> F (medium route)
    # (-40.98, -141.76),
    # Route 7: F -> G (medium route)
    # (-59.76, -134.67),
    # Route 8: G -> H (medium route)
    # (-75.78, -122.24),
    # Route 9: H -> I (medium route)
    # (-69.87, -142.90),
    # Route 10: I -> J (medium route)
    # (-69.84, -163.39),
    # Route 11: J -> K (long route)
    # (-85.20, -177.28),
    # Route 12: K -> L (long route)
    # (-70.45, -191.99),
    # Route 13: L -> M (long route)
    # (-51.69, -200.13),
    # Route 14: M -> N (long route)
    # (-50.16, -220.24),
    # Route 15: N -> O (long route)
    # (-53.70, -200.26),
    #(601.7160484446141, -126.74603548409573)
    (-642.2161592239, -366.9420546908),
]


def find_maps_directory() -> Path:
    """Find the maps directory (local maps folder in repository).
    
    Returns:
        Path to maps directory
        
    Raises:
        FileNotFoundError: If maps directory not found
    """
    candidate_paths = [
        # Path 1: Local maps folder in repository (PREFERRED - self-contained)
        Path('/root/colcon_ws/src/ackermann-vehicle-gzsim-ros2/maps'),
        # Path 2: Alternative location (backward compatibility)
        Path('/root/colcon_ws/src/ackermann-vehicle-gzsim-ros2/map2gazebo_maps'),
        # Path 3: External map2gazebo (fallback for old setups)
        Path('/root/colcon_ws/src/map2gazebo/maps'),
        # Path 4: Host path (if mounted differently)
        Path('/home/studente/ackermann_sim/src/ackermann-vehicle-gzsim-ros2/maps'),
    ]
    
    for path in candidate_paths:
        if (path / 'edges.json').exists() and (path / 'map.json').exists():
            return path
    
    raise FileNotFoundError(
        "Map files not found! Expected maps/ folder in repository with edges.json and map.json. "
        "Check that maps folder exists in ackermann-vehicle-gzsim-ros2/maps/"
    )


def wait_for_odometry(node, max_wait_time: float = 10.0):
    """Wait for odometry message to arrive.
    
    Args:
        node: ROS 2 node
        max_wait_time: Maximum time to wait in seconds
        
    Raises:
        SystemExit: If timeout occurs
    """
    import base_path_planner_node
    
    node.get_logger().info("Waiting for odometry...")
    start_time = node.get_clock().now()
    
    # Give subscription time to establish connection
    time.sleep(0.5)
    
    while base_path_planner_node.current_pose is None and rclpy.ok():
        elapsed = (node.get_clock().now() - start_time).nanoseconds / 1e9
        if elapsed > max_wait_time:
            node.get_logger().error("Timeout waiting for odometry! Check if Gazebo is running.")
            # Check if topic exists
            result = subprocess.run(['ros2', 'topic', 'list'], capture_output=True, text=True, timeout=2)
            if '/odom' in result.stdout:
                node.get_logger().error("Topic /odom exists but no messages received. Check if vehicle is spawned.")
            else:
                node.get_logger().error("Topic /odom does not exist!")
            rclpy.shutdown()
            exit(1)
        
        rclpy.spin_once(node, timeout_sec=0.1)
        if base_path_planner_node.current_pose is None:
            if int(elapsed * 10) % 10 == 0:  # Log every second
                node.get_logger().info(f"Waiting for current position... (elapsed: {elapsed:.1f}s)")
    
    if base_path_planner_node.current_pose is not None:
        node.get_logger().info("Odometry received!")


def get_start_position():
    """Get start position from current pose.
    
    Returns:
        Tuple of (start_x, start_y)
    """
    import base_path_planner_node
    
    if base_path_planner_node.current_pose is None:
        return None, None
    
    start_x = base_path_planner_node.current_pose.pose.pose.position.x
    start_y = base_path_planner_node.current_pose.pose.pose.position.y
    return start_x, start_y


def print_metrics(node, start: Tuple[float, float], goal: Tuple[float, float], 
                  path, metrics: dict):
    """Print path planning metrics.
    
    Args:
        node: ROS 2 node
        start: Start position
        goal: Goal position
        path: Planned path
        metrics: Metrics dictionary
    """
    goal_x, goal_y = goal
    
    node.get_logger().info("=" * 80)
    node.get_logger().info("PATH PLANNING METRICS")
    node.get_logger().info("=" * 80)
    node.get_logger().info(f"Start position: ({start[0]:.2f}, {start[1]:.2f})")
    node.get_logger().info(f"Goal position: ({goal_x:.2f}, {goal_y:.2f})")
    
    if path is None:
        node.get_logger().error("No path found!")
        node.get_logger().info("Metrics:")
        node.get_logger().info(f"  Computation time: {metrics['computation_time']*1000:.2f}ms")
        node.get_logger().info(f"  Nodes expanded: {metrics['nodes_expanded']}")
        return
    
    node.get_logger().info("=" * 80)
    node.get_logger().info("PATH PLANNING RESULTS")
    node.get_logger().info("=" * 80)
    node.get_logger().info(f"Path found: {len(path)} waypoints")
    
    # Print all metrics
    node.get_logger().info("")
    node.get_logger().info("1. PATH COST (Total Distance)")
    node.get_logger().info(f"   {metrics['path_cost']:.4f} meters")
    
    node.get_logger().info("")
    node.get_logger().info("2. COMPUTATION TIME")
    node.get_logger().info(f"   {metrics['computation_time']*1000:.4f} milliseconds")
    node.get_logger().info(f"   {metrics['computation_time']:.6f} seconds")
    
    node.get_logger().info("")
    node.get_logger().info("3. NODES EXPANDED")
    node.get_logger().info(f"   {metrics['nodes_expanded']} nodes explored")
    
    node.get_logger().info("")
    node.get_logger().info("4. MEMORY USAGE")
    node.get_logger().info(f"   {metrics['memory_usage']:.4f} MB (peak)")
    
    node.get_logger().info("")
    node.get_logger().info("5. OPTIMALITY")
    node.get_logger().info(f"   {'✓ Optimal (guaranteed shortest path)' if metrics['optimal'] else '✗ Not optimal'}")
    
    node.get_logger().info("")
    node.get_logger().info("=" * 80)
    
    if len(path) <= 10:
        node.get_logger().info(f"Full path: {path}")
    else:
        node.get_logger().info(f"Path preview: {path[:3]}...{path[-3:]}")


def move_vehicle(path, node):
    """Start following the path.
    
    Args:
        path: Planned path
        node: ROS 2 node
    """
    node.get_logger().info("Starting to move along path")
    node.path = path
    node.current_waypoint_idx = 0
    node.goal_reached = False
    node.path_following = True


def run_path_planner(node_class, planner_class, algorithm_name: str):
    """Main execution function for path planner scripts.
    
    Args:
        node_class: Path planner node class
        planner_class: Path planner class
        algorithm_name: Name of the algorithm (for logging)
    """
    rclpy.init()
    
    # Find maps directory
    try:
        maps_dir = find_maps_directory()
    except FileNotFoundError as e:
        print(f"Error: {e}")
        exit(1)
    
    edges_file = maps_dir / 'edges.json'
    map_file = maps_dir / 'map.json'
    polygons_file = maps_dir / 'road_polygons_merged.json'
    
    # Initialize planner
    if polygons_file.exists():
        planner = planner_class(str(edges_file), str(map_file), str(polygons_file))
    else:
        planner = planner_class(str(edges_file), str(map_file))
    
    # Initialize node
    node = node_class(planner)
    
    # Wait for odometry
    wait_for_odometry(node)
    
    if not rclpy.ok():
        rclpy.shutdown()
        exit(1)
    
    # Get start position
    start_x, start_y = get_start_position()
    if start_x is None:
        node.get_logger().error("Could not get start position!")
        rclpy.shutdown()
        exit(1)
    
    start = (start_x, start_y)
    
    # Get active goal (first uncommented)
    goal = ROUTE_GOALS[0]
    goal_x, goal_y = goal
    
    # Plan path and get metrics
    path, metrics = planner.search(start, goal)
    
    # Print metrics
    print_metrics(node, start, goal, path, metrics)
    
    if path is None:
        rclpy.shutdown()
        exit(1)
    
    # Start following path
    move_vehicle(path, node)
    node.get_logger().info(f"Path following started. Total waypoints: {len(path)}")
    
    # Main loop - follow path (control loop runs via timer)
    try:
        while rclpy.ok() and not node.goal_reached:
            rclpy.spin_once(node, timeout_sec=0.1)
    except KeyboardInterrupt:
        node.get_logger().info("Interrupted by user")
    finally:
        node.stop_vehicle()
        node.destroy_node()
        rclpy.shutdown()

